project:
  type: website
  output-dir: build
  preview:
    host: 0.0.0.0
    port: 4200

website:
  title: "blog.yifen9.li"
  navbar:
    right:
      - icon: github
        href: https://github.com/yifen9
  # repo-url: https://github.com/yifen9/yifen9.li
  # repo-subdir: sites/blog
  # repo-actions: [source, edit, issue]

format:
  html:
    include-after-body:
      - _includes/footer.html