project:
  output-dir: build
  resources:
    - avatar.png
    - cv.pdf
    - cv.tex
    - gpa/**
    - lang/**

date: now
date-format: "YYYY-MM-DDTHH:mm:ssZ"

format:
  html:
    include-after-body:
      - _includes/footer.html