---
title: "Li Yifeng"
---

## Info

- Base
  - Li Yifeng (李艺峰)
  - November 9, 2005
  - Shenzhen (CN) => Trento (IT)
- Education
  - Bachelor of Computer Science, University of Trento, 2024 - Current
- Applications
  - ORCID SpringRank, Apr, 2024 - Current
    - [GitHub](https://github.com/yifen9/orcid-springrank)
    - [Kaggle (old)](https://www.kaggle.com/datasets/yifen9/orcid-dataset)
    - [Presentation (old)](https://assets.yifen9.li/apps/orcid-springrank/presentation.pdf)
  - Reddit Archive, Sep - Nov, 2025
    - [GitHub](https://github.com/open-run-org/archive)
    - [Website](https://archive.open-run.org)
  - GitHub Auto Inviter, Oct, 2025
    - [GitHub](https://github.com/unitn-ap-2025/api)
    - [OpenAPI](https://unitn-ap-2025.github.io/api)
- Packages
  - DynamicSpringRank.jl, Nov, 2025 - Current
    - [Documentation](https://dsr-jl.apps.yifen9.li)
    - [GitHub](https://github.com/yifen9/DynamicSpringRank.jl)
  - SpringRank.jl, Oct - Nov, 2025
    - [Documentation](https://sr-jl.apps.yifen9.li)
    - [GitHub](https://github.com/yifen9/SpringRank.jl)
  - c-labkit, Oct, 2025
    - [GitHub](https://github.com/yifen9/c-labkit)
    - [CLI Package](https://github.com/yifen9/c-labkit/pkgs/container/c-labkit-cli)

## Files

- [Avatar](./avatar.png)
- [Curriculum Vitae](./cv.pdf)

- Grade Point Average
  - [Bachelor UniTrento](./gpa/bsc_unitn.pdf)
- Language Certificates
  - [English IELTS](./lang/en_ielts.pdf)
  - [Italian UniTrento](./lang/it_unitn.png)
  - [German UniTrento](./lang/de_unitn.png)

## Links

- Websites
  - [Blog](https://blog.yifen9.li)
  - [UniTrento L-31 Boardgame Club](https://bg.unitn.yifen9.li)
  - [UniTrento L-31 Lab](https://l31.unitn.yifen9.li)
  - [UniTrento Problemset](https://pset.unitn.yifen9.li)
  - [UniTrento UniOpera Printer Service](https://opera.unitn.yifen9.li)
- E-mail
  - [mail@yifen9.li](mailto:mail@yifen9.li)
  - [yifeng.li@studenti.unitn.it](mailto:yifeng.li@studenti.unitn.it)
- Social Media
  - [GitHub](https://github.com/yifen9)
  - [LinkedIn](https://www.linkedin.com/in/yifen9li)
  - [Telegram](https://t.me/yifen9)
