services:
  yifen9.li:
    image: ghcr.io/yifen9/yifen9.li
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: yifen9.li
    working_dir: /workspace
    env_file:
      - .dev.env
    ports:
      - "8080:8080"
    volumes:
      - "..:/workspace"
    command: >
      bash -c "
        exec sleep infinity
      "